### ISSUE TITLE
Incorrectly comment marking the workflow run as failed

### ISSUE THREAD

**Issue by joshjohanning** [joshjohanning/approveops#4]
![image](https://user-images.githubusercontent.com/19912012/189935622-66882820-91c7-4077-bc3e-f64484919658.png)

```yml
      - name: ApproveOps - Approvals in IssueOps
        uses: joshjohanning/approveops@v1
        with:
          app-id: 170284 # The GitHub App ID; ie: 170284
          app-private-key: ${{ secrets.PRIVATE_KEY }} # Private key for the GitHub App that is installed on the repo; e.g.: ${{ secrets.PRIVATE_KEY }}
          team-name: approver-team # The name of the team in GitHub to check for the approval command; e.g.: approver-team
          fail-if-approval-not-found: false
```

It should say there was no approval, but if we aren't failing if approval not found, we shouldn't say 

> :no_entry_sign: :no_entry: Marking the workflow run as failed`
